##################################################################
#  Machine Dependencies - this file is included automatically
#     into the main Makefile
#
# This file contains definitions below for x86 running Linux
# It has *not* been tested!
##################################################################

HOSTCFLAGS = -Dx86 -DLINUX

#-----------------------------------------------------------------
# Do not put anything below this point - it will be destroyed by
# "make depend"
#
# DO NOT DELETE THIS LINE -- make depend uses it
# DEPENDENCIES MUST END AT END OF FILE
# IF YOU PUT STUFF HERE IT WILL GO AWAY
# see make depend above
